apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container
          image: ahmednageh08/node-app:1.1
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-configmap
            - secretRef:
                name: app-secret